name: Deploy to Heroku and Test API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Start API Server
        run: npm start &

      - name: Wait for API Server to Start
        run: sleep 10s

      - name: Run Unit Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2 # This actions copy the repository on the environment
      - uses: akhileshns/heroku-deploy@v3.12.12 # This action deploys the content on Heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} #The Heroku api key we stored on our repo secret
          heroku_app_name: "mission-1-backend" #The name of your heroku app - Must be unique in Heroku
          heroku_email: "boulom.vatthana@gmail.com" #Your heroku yuser name
